### ISSUE TITLE
Исправить вычисление pw

### ISSUE THREAD

**Issue by artembark** [VityaSchel/asurso#3]
Если посмотреть оригинальный JS скрипт, то там строчка pw.val(pw2.substr(0, pw.val().length).
То есть pw это первые n символов хэша, где n - это длина пароля.
https://asurso.ru/static/dist/pages/about/js/about.js?ver=5.0.59053.776

**Comment by VityaSchel** [comment]
ой это я свой пароль слил чтоли

**Comment by VityaSchel** [comment]
ывывы асу щас сделаем

**Comment by VityaSchel** [comment]
Исправил, проверьте пожалуйста если не сложно
